# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/jediminer543/JMT-MCMT/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="jmt_mcmt" #mandatory
version="${file.jarVersion}" #mandatory
displayName="JMT MCMT"
# updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/jediminer543/JMT-MCMT"
# logoFile="examplemod.png" #optional
credits="The glorious power of Coremods" #optional
authors="jediminer543"
# The description text for the mod (multi line!) (#mandatory)
description='''
A bunch of core mod based assembly hacks that allow for the parallelised running of mineccraft

Absurd, likely incompatible with everything, but somehow works
'''
[[dependencies.jmt_mcmt]] #optional
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.jmt_mcmt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="SERVER"
